### PR TITLE
updates: more defensive behaviour by default, more reasonable cache_path handling, more tests

### PR DESCRIPTION
**Pull request by karlicoss**
addresses https://github.com/karlicoss/cachew/issues/12 , https://github.com/karlicoss/cachew/issues/17

### CODE REVIEW

**Comment by karlicoss** [comment]
@seanbreckenridge you might be interested as you have some relevant changes in your HPI: https://github.com/seanbreckenridge/HPI/blob/64ea5df3a24298875f2700aaa4a5fa63051b7599/my/core/common.py#L274-L302

- [mkdir](https://github.com/seanbreckenridge/HPI/blob/64ea5df3a24298875f2700aaa4a5fa63051b7599/my/core/common.py#L283-L288)
  Now, mkdir for `cache_path.parent` will always be called, so at least nothing would crash anymore and force you to create dirs in advance.
  The only thing I'm not sure about yet, is assuming that `cache_path` itself is a dir if it didn't exist. It's a very reasonable default, but it feels that it's also good to allow to point directly at the cache. It should be fairly rare (I'd rather get the default cache dir & naming right so the user doesn't have to fiddle with explicit params), so I guess I have a couple of options here:
  - extra argument? e.g `force_file=True` or something like that?
  - let the user `touch` the path in advance, so on the next cachew run it detects a regular file and overwrites it with a proper database

- [cache file names](https://github.com/seanbreckenridge/HPI/blob/64ea5df3a24298875f2700aaa4a5fa63051b7599/my/core/common.py#L290-L295): I've switched to using `f'{func.__module__}:{func.__qualname__}'` for cache file names to avoid clashes and for more clarity. As far as I know, python identifiers are valid filenames, but maybe I'm wrong.

- I'm also thinking to rename `hashf` (feels a bit cryptic?) to something more clear (backward compatible of course), maybe `key`, or `depends_on`? Wonder what do you think?

**Comment by seanbreckenridge** [comment]
> let the user touch the path in advance, so on the next cachew run it detects a regular file and overwrites it with a proper database

Seems a bit un-intuitive, especially since `cachew` is a decorator, so someone would have to go out of their way to create another decorator, or call something somewhere else related to this, when its meant to be pretty transparent. something along the lines of  `force_file=True` seems okay, but Im still unsure on why someone would want that.

> `func.__module__`

Ah, nice. I knew there must've been something like that.

> `hashf`

hmm. I don't think `hashf` is that bad, I have had to come back to the readme here because I've forgotten if before though. `key` might cause some confusion since thats used in the python stdlib. 

`depends_on` sounds a bit nicer, but `hashf` is actually what this is -- its a hash function to check if the inputs have changed. 

Would be fine with changing it to `depends_on`, reads a bit nicer in the signature.

**Comment by karlicoss** [comment]
> but Im still unsure on why someone would want that

One example is if you want the database path itself depend on the argument, e.g. you want a separate cache for each argument (instead of invalidating it every time). I guess not a big issue to use a directory per argument, but still.
Kind of tangential, but I also thought of suppoting that usecase directly (e.g. a proper LRU cache, with a database table per argument), but it's going to be somewhat more complex and potentially error prone, so I've been hesitant it so far.

**Comment by karlicoss** [comment]
All right, done! I'll test in it action for a bit before doing the pypi release, but you can use master if you're keen

**Comment by karlicoss** [comment]
And it's on pypi now!

**Comment by seanbreckenridge** [comment]
Sweet. I shall try and implement some of the changes into my branch at some point soon.

**Comment by seanbreckenridge** [comment]
[Was able to](https://github.com/seanbreckenridge/HPI/commit/092e84f2aaed62edfe77f8a76120b131786d7479) remove my `cachewpath` function, and instead I can use `mcachew`. For exmaple, for `my.commits`, using the path as the location in `/tmp/cachew`, I do:

```python
@mcachew(
    depends_on=_repo_depends_on,
    cache_path=lambda p: str(
        cache_dir() / simplify_path(p) / cachew.cname(_cached_commits)
    ),
    force_file=True,
    logger=log,
)
def _cached_commits(_repo: Path) -> Iterator[Commit]:
    log.info("processing %s", _repo)
```

That creates a structure like:

```
├── homeseanReposcoderradioshownotes
│   └── my.coding.commits:_cached_commits
├── homeseanReposcommandsdiscordpystarter
│   └── my.coding.commits:_cached_commits
├── homeseanReposcookiecutterlib
│   └── my.coding.commits:_cached_commits
├── homeseanReposcookiecuttertemplate
│   └── my.coding.commits:_cached_commits
```

Not sure if I can get this without importing `cachew.cname` (could always vendorize it into `HPI`), but I'm quite happy with this.

**Comment by karlicoss** [comment]
Cool! I think you can simplify even further, why are you using `force_file=True`? By default, it [treats the path as the directory now](https://github.com/karlicoss/cachew/blob/6f3c4d5fe5f7f28a73c906a4024d2f59bca9d3c4/src/cachew/__init__.py#L898-L912). So I think you should be able to simply specify 
```
@mcachew(
    depends_on=_repo_depends_on,
    cache_path=lambda p: cache_dir() / simplify_path(p)
    logger=log,
)
```

**Comment by seanbreckenridge** [comment]
It doesnt really affect the caching, it just creates an extra directory, like: 

image

I don't think its its any different functionally, its just so that I can view the size of the database in my file viewer quicker when I'm debugging/looking in that directory.

image

**Pull request merged**
